version: '3.8'

services:
  # Główna aplikacja dokumentacji
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dialogware-docs
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=mongodb://mongo:27017/dialogware-docs
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ANALYTICS_KEY=${ANALYTICS_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./docs:/app/docs
      - ./public:/app/public
      - node_modules:/app/node_modules
    depends_on:
      - redis
      - mongo
      - search
      - minio
    networks:
      - dialogware-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis dla cache i sesji
  redis:
    image: redis:alpine
    container_name: dialogware-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dialogware-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB dla przechowywania danych
  mongo:
    image: mongo:5
    container_name: dialogware-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - dialogware-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  # Elasticsearch dla wyszukiwania
  search:
    image: elasticsearch:8.7.0
    container_name: dialogware-search
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - dialogware-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status.*green'"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MinIO dla przechowywania plików
  minio:
    image: minio/minio
    container_name: dialogware-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - dialogware-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx jako reverse proxy
  nginx:
    image: nginx:alpine
    container_name: dialogware-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./public:/usr/share/nginx/html
    depends_on:
      - docs
    networks:
      - dialogware-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus dla monitoringu
  prometheus:
    image: prom/prometheus
    container_name: dialogware-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - dialogware-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Grafana dla wizualizacji metryk
  grafana:
    image: grafana/grafana
    container_name: dialogware-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - dialogware-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dialogware-network:
    driver: bridge

volumes:
  node_modules:
  redis_data:
  mongodb_data:
  elasticsearch_data:
  minio_data:
  prometheus_data:
  grafana_data:
